PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dgfr: <http://colin.maudry.com/ontologies/dgfr#>
PREFIX xs: <http://www.w3.org/2001/XMLSchema#>
PREFIX apf: <http://jena.hpl.hp.com/ARQ/property#>
PREFIX schema: <http://schema.org/>
PREFIX organizations: <https://www.data.maudry.com/fr/organizations/>

construct

{
  ?organization a foaf:Organization ;
    dct:identifier ?id ;
    schema:url ?urlAsUri ;
    foaf:name ?name ;
    rdfs:label ?name ;
    dct:description ?description ;
    dct:created ?createdAsDateTime ;
    dct:modified ?modifiedAsDateTime ;
    dgfr:slug ?slug ;
    dgfr:views ?views ;
    dgfr:followers ?followers ;
    dgfr:visits ?visits ;
    dgfr:hits ?hits ;
    dgfr:uniqueVisitors ?unique_visitors ;
    dgfr:datasets ?datasets ;
    dgfr:members ?members ;
    dgfr:reuses ?permitted_reuses ;
    dgfr:hasMadeReuses ?reuses ;
    dgfr:publicService ?lcPublicService .  
}
from <file:../csv/organizations.csv#delimiter=%3B;encoding=utf-8>
  where {  
  bind(uri(concat("https://www.data.maudry.com/fr/organizations/",?slug)) as ?organization)
  bind(uri(?url) as ?urlAsUri)
  bind(xs:boolean(if(?public_service="",false,lcase(?public_service))) as ?lcPublicService)
  bind(xs:dateTime(?created_at) as ?createdAsDateTime)
  bind(xs:dateTime(?last_modified) as ?modifiedAsDateTime)
  bind(xs:integer(?metric_views) as ?views)
  bind(xs:integer(?metric_followers) as ?followers)
  bind(xs:integer(?metric_nb_hits) as ?hits)
  bind(xs:integer(?metric_nb_visits) as ?visits)
  bind(xs:integer(?metric_nb_uniq_visitors) as ?unique_visitors)
  bind(xs:integer(?metric_members) as ?members)
  bind(xs:integer(?metric_permitted_reuses) as ?permitted_reuses)
  bind(xs:integer(?metric_reuses) as ?reuses)
  bind(xs:integer(?metric_datasets) as ?datasets)
  }
  
  